# Generated by Django 6.0.4 on 2026-06-15 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('INTERVIEW', 'Interview Round'), ('SELECTED', 'Selected'), ('OFFER_RECEIVED', 'Offer Received'), ('OFFER_ACCEPTED', 'Offer Accepted')], default='APPLIED', max_length=20)),
                ('cover_letter', models.TextField(blank=True)),
                ('resume_used', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('skill_match_percentage', models.IntegerField(default=0, help_text='0-100')),
                ('notes', models.TextField(blank=True, help_text='Notes from company/admin')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.student')),
            ],
            options={
                'ordering': ['-applied_on'],
                'unique_together': {('student', 'job')},
            },
        ),
    ]
