# Generated by Django 6.0.4 on 2026-06-15 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_skills', models.TextField(help_text='Enter skills separated by commas')),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('INTERNSHIP', 'Internship'), ('CONTRACT', 'Contract')], default='FULL_TIME', max_length=20)),
                ('experience_required', models.CharField(choices=[('FRESHER', 'Fresher'), ('0-1', '0-1 Year'), ('1-2', '1-2 Years'), ('2-5', '2-5 Years'), ('5+', '5+ Years')], default='FRESHER', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('salary_min', models.IntegerField(blank=True, help_text='Minimum salary in LPA', null=True)),
                ('salary_max', models.IntegerField(blank=True, help_text='Maximum salary in LPA', null=True)),
                ('salary_currency', models.CharField(default='INR', max_length=10)),
                ('qualification_required', models.CharField(choices=[('12TH', '12th Pass'), ('DIPLOMA', 'Diploma'), ('BACHELORS', 'Bachelors'), ('MASTERS', 'Masters')], default='BACHELORS', max_length=100)),
                ('min_cgpa', models.FloatField(default=5.0, help_text='Minimum CGPA required')),
                ('allowed_branches', models.CharField(help_text='Allowed branches separated by commas (e.g., CSE, ECE, ME)', max_length=200)),
                ('application_deadline', models.DateTimeField()),
                ('max_applications', models.IntegerField(default=100)),
                ('applications_received', models.IntegerField(default=0)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.company')),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
    ]
