# Generated by Django 6.0.4 on 2026-06-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('total_companies', models.IntegerField(default=0)),
                ('total_jobs', models.IntegerField(default=0)),
                ('total_applications', models.IntegerField(default=0)),
                ('students_placed', models.IntegerField(default=0)),
                ('pending_verifications', models.IntegerField(default=0)),
                ('average_salary', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Admin Stats',
            },
        ),
    ]
